export const endpoints = {
  auth: {
    login: "/auth/login/",
    register: "/auth/register/",
    logout: "/auth/logout/",
    refresh: "/auth/token/refresh/",
    profile: "/auth/profile/",
    patientProfile: "/auth/profile/patient/",
    forgotPassword: "/auth/password/forgot/",
    resetPassword: "/auth/password/reset/",
    verifyEmail: "/auth/verify/email/",
    verifyPhone: "/auth/verify/phone/",
    completeOnboarding: "/auth/onboarding/complete/",
  },
  medications: {
    list: "/medications/",
    detail: (id: string) => `/medications/${id}/`,
    adherence: (id: string) => `/medications/${id}/adherence/`,
    ocr: "/medications/ocr/",
  },
  pharmacies: { list: "/pharmacies/", detail: (id: string) => `/pharmacies/${id}/` },
  products: { list: "/products/", detail: (id: string) => `/products/${id}/` },
  orders: {
    list: "/orders/",
    checkout: "/orders/checkout/",
    detail: (id: string) => `/orders/${id}/`,
  },
  preorders: { list: "/pre-order-requests/" },
  pharmacists: { list: "/pharmacists/", detail: (id: string) => `/pharmacists/${id}/` },
  pharmacistApplications: {
    current: "/pharmacists/application/",
  },
  conversations: {
    list: "/conversations/",
    detail: (id: string) => `/conversations/${id}/`,
    messages: (id: string) => `/conversations/${id}/messages/`,
  },
  ocr: { extract: "/ocr/extractions/" },
  refills: { list: "/refill-requests/" },
  pharmacyWorkspace: {
    register: "/pharmacy/register/",
    access: "/pharmacy/access/",
    application: "/pharmacy/application/",
    applications: "/pharmacy/applications/",
    licenses: "/pharmacy/licenses/",
    pharmacists: "/pharmacy/pharmacists/",
    dashboard: "/pharmacy/dashboard/",
    orders: "/pharmacy/orders/",
    orderStatus: (id: string) => `/pharmacy/orders/${id}/status/`,
    inventory: "/pharmacy/inventory/",
    inventoryItem: (id: string) => `/pharmacy/inventory/${id}/`,
    customers: "/pharmacy/customers/",
    refills: "/pharmacy/refill-requests/",
    refillStatus: (id: string) => `/pharmacy/refill-requests/${id}/status/`,
  },
  admin: {
    verifications: "/admin/verifications/",
    verification: (id: string) => `/admin/verifications/${id}/`,
    pharmacistVerifications: "/admin/pharmacist-verifications/",
    pharmacistVerification: (id: string) => `/admin/pharmacist-verifications/${id}/`,
  },
} as const;
