"""preorder requests

Revision ID: 0cd34eef93f8
Revises: c375a82f7368
Create Date: 2026-09-27 16:05:29.269433
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0cd34eef93f8'
down_revision: Union[str, None] = 'c375a82f7368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preorder_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_user_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('pharmacy_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('requested', 'accepted', 'declined', 'available', name='preorderstatus', native_enum=False), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preorder_requests_patient_user_id'), 'preorder_requests', ['patient_user_id'], unique=False)
    op.create_index(op.f('ix_preorder_requests_pharmacy_id'), 'preorder_requests', ['pharmacy_id'], unique=False)
    op.create_index(op.f('ix_preorder_requests_product_id'), 'preorder_requests', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_preorder_requests_product_id'), table_name='preorder_requests')
    op.drop_index(op.f('ix_preorder_requests_pharmacy_id'), table_name='preorder_requests')
    op.drop_index(op.f('ix_preorder_requests_patient_user_id'), table_name='preorder_requests')
    op.drop_table('preorder_requests')
    # ### end Alembic commands ###

