"""pharmacy vendor credentials

Revision ID: 4a1af26a5714
Revises: 23fb5d3c5649
Create Date: 2026-09-27 15:44:10.284357
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4a1af26a5714'
down_revision: Union[str, None] = '23fb5d3c5649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pharmacists', sa.Column('license_issued_by', sa.String(length=200), nullable=True))
    op.add_column('pharmacists', sa.Column('license_document_url', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pharmacists', 'license_document_url')
    op.drop_column('pharmacists', 'license_issued_by')
    # ### end Alembic commands ###

