"""commerce workspace

Revision ID: c375a82f7368
Revises: 4a1af26a5714
Create Date: 2026-09-27 16:03:01.712761
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c375a82f7368'
down_revision: Union[str, None] = '4a1af26a5714'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reference', sa.String(length=30), nullable=False),
    sa.Column('patient_user_id', sa.String(length=36), nullable=False),
    sa.Column('pharmacy_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('placed', 'pharmacy_review', 'accepted', 'preparing', 'ready_for_pickup', 'out_for_delivery', 'completed', 'cancelled', name='orderstatus', native_enum=False), nullable=False),
    sa.Column('payment_status', sa.Enum('pending', 'paid', 'failed', name='paymentstatus', native_enum=False), nullable=False),
    sa.Column('payment_method', sa.String(length=40), nullable=False),
    sa.Column('fulfillment_method', sa.String(length=30), nullable=False),
    sa.Column('recipient_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('delivery_address', sa.String(length=500), nullable=True),
    sa.Column('prescription_file_name', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('delivery_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_patient_user_id'), 'orders', ['patient_user_id'], unique=False)
    op.create_index(op.f('ix_orders_pharmacy_id'), 'orders', ['pharmacy_id'], unique=False)
    op.create_index(op.f('ix_orders_reference'), 'orders', ['reference'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pharmacy_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('generic_name', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('form', sa.String(length=80), nullable=False),
    sa.Column('strength', sa.String(length=80), nullable=False),
    sa.Column('pack_size', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('stock_count', sa.Integer(), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('requires_prescription', sa.Boolean(), nullable=False),
    sa.Column('requires_pharmacist_review', sa.Boolean(), nullable=False),
    sa.Column('preorder_supported', sa.Boolean(), nullable=False),
    sa.Column('estimated_restock_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_pharmacy_id'), 'products', ['pharmacy_id'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_table('refill_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_user_id', sa.String(length=36), nullable=False),
    sa.Column('pharmacy_id', sa.String(length=36), nullable=False),
    sa.Column('medication_name', sa.String(length=200), nullable=False),
    sa.Column('strength', sa.String(length=80), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('requested', 'accepted', 'declined', 'ready', name='refillstatus', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refill_requests_patient_user_id'), 'refill_requests', ['patient_user_id'], unique=False)
    op.create_index(op.f('ix_refill_requests_pharmacy_id'), 'refill_requests', ['pharmacy_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('strength', sa.String(length=80), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('requires_prescription', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_refill_requests_pharmacy_id'), table_name='refill_requests')
    op.drop_index(op.f('ix_refill_requests_patient_user_id'), table_name='refill_requests')
    op.drop_table('refill_requests')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_pharmacy_id'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_orders_reference'), table_name='orders')
    op.drop_index(op.f('ix_orders_pharmacy_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_patient_user_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###

